name: pr
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          ignore_words_list: crate,MIS

  validate:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - run: sudo apt-get install -y fuse3 fuse-overlayfs pkg-config libsystemd-dev build-essential libelf-dev libseccomp-dev libclang-dev libssl-dev
        - run: make validate.cargo

  #test:
  #  runs-on: ubuntu-latest
  #  steps:
  #      - uses: actions/checkout@v4
  #      - run: sudo apt-get install -y fuse3 fuse-overlayfs pkg-config libsystemd-dev build-essential libelf-dev libseccomp-dev libclang-dev libssl-dev
  #      - run: make test
